spring.application.name=RoomBook
server.port=8080

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.datasource.url=jdbc:mariadb://db:3306/roombook
spring.datasource.username=roombook
spring.datasource.password=roombook
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

#spring.jpa.database-platform=org.hibernate.dialect.MariaDBDialect
